"""initial_schema

Revision ID: acf2ae49a604
Revises:
Create Date: 2026-02-09 16:36:00.091161

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "acf2ae49a604"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation_presets",
        sa.Column("id", sa.String(length=21), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_presets")),
        sa.UniqueConstraint("name", name=op.f("uq_generation_presets_name")),
    )
    op.create_table(
        "methodology_settings",
        sa.Column("id", sa.String(length=21), nullable=False),
        sa.Column("section_key", sa.String(length=100), nullable=False),
        sa.Column("current_content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_methodology_settings")),
        sa.UniqueConstraint("section_key", name=op.f("uq_methodology_settings_section_key")),
    )
    op.create_table(
        "voice_clones",
        sa.Column("id", sa.String(length=21), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("avatar_path", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_voice_clones")),
    )
    op.create_table(
        "content",
        sa.Column("id", sa.String(length=21), nullable=False),
        sa.Column("clone_id", sa.String(length=21), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("content_current", sa.Text(), nullable=False),
        sa.Column("content_original", sa.Text(), nullable=False),
        sa.Column("input_text", sa.Text(), nullable=False),
        sa.Column("generation_properties", sa.JSON(), nullable=True),
        sa.Column("authenticity_score", sa.Integer(), nullable=True),
        sa.Column("score_dimensions", sa.JSON(), nullable=True),
        sa.Column("topic", sa.String(length=200), nullable=True),
        sa.Column("campaign", sa.String(length=200), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("preset_id", sa.String(length=21), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clone_id"], ["voice_clones.id"], name=op.f("fk_content_clone_id_voice_clones")
        ),
        sa.ForeignKeyConstraint(
            ["preset_id"],
            ["generation_presets.id"],
            name=op.f("fk_content_preset_id_generation_presets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content")),
    )
    with op.batch_alter_table("content", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_content_clone_id"), ["clone_id"], unique=False)

    op.create_table(
        "merged_clone_sources",
        sa.Column("id", sa.String(length=21), nullable=False),
        sa.Column("merged_clone_id", sa.String(length=21), nullable=False),
        sa.Column("source_clone_id", sa.String(length=21), nullable=False),
        sa.Column("weights", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merged_clone_id"],
            ["voice_clones.id"],
            name=op.f("fk_merged_clone_sources_merged_clone_id_voice_clones"),
        ),
        sa.ForeignKeyConstraint(
            ["source_clone_id"],
            ["voice_clones.id"],
            name=op.f("fk_merged_clone_sources_source_clone_id_voice_clones"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merged_clone_sources")),
    )
    op.create_table(
        "methodology_versions",
        sa.Column("id", sa.String(length=21), nullable=False),
        sa.Column("settings_id", sa.String(length=21), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("trigger", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["settings_id"],
            ["methodology_settings.id"],
            name=op.f("fk_methodology_versions_settings_id_methodology_settings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_methodology_versions")),
    )
    with op.batch_alter_table("methodology_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_methodology_versions_settings_id"), ["settings_id"], unique=False
        )

    op.create_table(
        "voice_dna_versions",
        sa.Column("id", sa.String(length=21), nullable=False),
        sa.Column("clone_id", sa.String(length=21), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("prominence_scores", sa.JSON(), nullable=True),
        sa.Column("trigger", sa.String(length=50), nullable=False),
        sa.Column("model_used", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clone_id"],
            ["voice_clones.id"],
            name=op.f("fk_voice_dna_versions_clone_id_voice_clones"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_voice_dna_versions")),
    )
    with op.batch_alter_table("voice_dna_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_voice_dna_versions_clone_id"), ["clone_id"], unique=False
        )

    op.create_table(
        "writing_samples",
        sa.Column("id", sa.String(length=21), nullable=False),
        sa.Column("clone_id", sa.String(length=21), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=False),
        sa.Column("content_type_detected", sa.String(length=50), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("length_category", sa.String(length=20), nullable=True),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("source_filename", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clone_id"], ["voice_clones.id"], name=op.f("fk_writing_samples_clone_id_voice_clones")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_writing_samples")),
    )
    with op.batch_alter_table("writing_samples", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_writing_samples_clone_id"), ["clone_id"], unique=False)

    op.create_table(
        "content_versions",
        sa.Column("id", sa.String(length=21), nullable=False),
        sa.Column("content_id", sa.String(length=21), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("trigger", sa.String(length=50), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"], ["content.id"], name=op.f("fk_content_versions_content_id_content")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_versions")),
    )
    with op.batch_alter_table("content_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_content_versions_content_id"), ["content_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("content_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_content_versions_content_id"))

    op.drop_table("content_versions")
    with op.batch_alter_table("writing_samples", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_writing_samples_clone_id"))

    op.drop_table("writing_samples")
    with op.batch_alter_table("voice_dna_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_voice_dna_versions_clone_id"))

    op.drop_table("voice_dna_versions")
    with op.batch_alter_table("methodology_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_methodology_versions_settings_id"))

    op.drop_table("methodology_versions")
    op.drop_table("merged_clone_sources")
    with op.batch_alter_table("content", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_content_clone_id"))

    op.drop_table("content")
    op.drop_table("voice_clones")
    op.drop_table("methodology_settings")
    op.drop_table("generation_presets")
    # ### end Alembic commands ###
